// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

// ===========================================================================
// Beg of ThingPipeDone

// ThingPipeDone returns a channel to receive every `inp` before close and a channel to signal this closing.
func ThingPipeDone(inp <-chan Thing) (out <-chan Thing, done <-chan struct{}) {
	cha := make(chan Thing)
	doit := make(chan struct{})
	go pipeThingDone(cha, doit, inp)
	return cha, doit
}

func pipeThingDone(out chan<- Thing, done chan<- struct{}, inp <-chan Thing) {
	defer close(out)
	defer close(done)
	for i := range inp {
		out <- i
	}
	done <- struct{}{}
}

// End of ThingPipeDone
