// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// minimal adjustments:
// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// original found in $GOROOT/test/chan/sieve2.go

// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

import "container/ring"

// Note: SendThingProxy imports "container/ring" for the expanding buffer.

// ===========================================================================
// Beg of SendThingProxy

// BufferThingCAP is the capacity of the buffered proxy channel in `SendThingProxy`
const BufferThingCAP = 10

// BufferThingQUE is the allocated size of the circular queue in `SendThingProxy`
const BufferThingQUE = 16

// SendThingProxy returns a channel to serve as a sending proxy to 'out'.
// Uses a goroutine to receive values from 'out' and store them
// in an expanding buffer, so that sending to 'out' never blocks.
//  Note: the expanding buffer is implemented via "container/ring"
func SendThingProxy(out chan<- Thing) chan<- Thing {
	proxy := make(chan Thing, BufferThingCAP)
	go func() {
		n := BufferThingQUE // the allocated size of the circular queue
		first := ring.New(n)
		last := first
		var c chan<- Thing
		var e Thing
		for {
			c = out
			if first == last {
				// buffer empty: disable output
				c = nil
			} else {
				e = first.Value.(Thing)
			}
			select {
			case e = <-proxy:
				last.Value = e
				if last.Next() == first {
					// buffer full: expand it
					last.Link(ring.New(n))
					n *= 2
				}
				last = last.Next()
			case c <- e:
				first = first.Next()
			}
		}
	}()
	return proxy
}

// End of SendThingProxy
