// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

import "time"

// ===========================================================================
// Beg of ThingStrew - scatter them

// ThingStrew returns a slice (of size = size) of channels
// one of which shall receive each inp before close.
func ThingStrew(inp <-chan Thing, size int) (outS [](<-chan Thing)) {
	chaS := make(map[chan Thing]struct{}, size)
	for i := 0; i < size; i++ {
		chaS[make(chan Thing)] = struct{}{}
	}

	go strewThing(inp, chaS)

	outS = make([]<-chan Thing, size)
	i := 0
	for c := range chaS {
		outS[i] = (<-chan Thing)(c) // convert `chan` to `<-chan`
		i++
	}

	return outS
}

// c strewThing(inp <-chan Thing, outS ...chan<- Thing) {
// Note: go does not convert the passed slice `[]chan Thing` to `[]chan<- Thing` automatically.
// So, we do neither here, as we are lazy (we just call an internal helper function).
func strewThing(inp <-chan Thing, outS map[chan Thing]struct{}) {

	for i := range inp {
		for !trySendThing(i, outS) {
			time.Sleep(time.Millisecond * 10) // wait a little before retry
		} // !sent
	} // inp

	for o := range outS {
		close(o)
	}
}

func trySendThing(inp Thing, outS map[chan Thing]struct{}) bool {

	for o := range outS {

		select { // try to send
		case o <- inp:
			return true
		default:
			// keep trying
		}

	} // outS
	return false
}

// End of ThingStrew - scatter them
// ===========================================================================
