// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

import "sync"

// ===========================================================================
// Beg of PipeThingSeen/ForkThingSeen - an "I've seen this Thing before" filter / fork

// PipeThingSeen returns a channel to receive
// all `inp`
// not been seen before
// while silently dropping everything seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
// Note: PipeThingFilterNotSeenYet might be a better name, but is fairly long.
func PipeThingSeen(inp <-chan Thing) (out <-chan Thing) {
	cha := make(chan Thing)
	go pipeThingSeenAttr(cha, inp, nil)
	return cha
}

// PipeThingSeenAttr returns a channel to receive
// all `inp`
// whose attribute `attr` has
// not been seen before
// while silently dropping everything seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
// Note: PipeThingFilterAttrNotSeenYet might be a better name, but is fairly long.
func PipeThingSeenAttr(inp <-chan Thing, attr func(a Thing) interface{}) (out <-chan Thing) {
	cha := make(chan Thing)
	go pipeThingSeenAttr(cha, inp, attr)
	return cha
}

// ForkThingSeen returns two channels, `new` and `old`,
// where `new` is to receive
// all `inp`
// not been seen before
// and `old`
// all `inp`
// seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
func ForkThingSeen(inp <-chan Thing) (new, old <-chan Thing) {
	cha1 := make(chan Thing)
	cha2 := make(chan Thing)
	go forkThingSeenAttr(cha1, cha2, inp, nil)
	return cha1, cha2
}

// ForkThingSeenAttr returns two channels, `new` and `old`,
// where `new` is to receive
// all `inp`
// whose attribute `attr` has
// not been seen before
// and `old`
// all `inp`
// seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
func ForkThingSeenAttr(inp <-chan Thing, attr func(a Thing) interface{}) (new, old <-chan Thing) {
	cha1 := make(chan Thing)
	cha2 := make(chan Thing)
	go forkThingSeenAttr(cha1, cha2, inp, attr)
	return cha1, cha2
}

func pipeThingSeenAttr(out chan<- Thing, inp <-chan Thing, attr func(a Thing) interface{}) {
	defer close(out)

	if attr == nil { // Make `nil` value useful
		attr = func(a Thing) interface{} { return a }
	}

	seen := sync.Map{}
	for i := range inp {
		if _, visited := seen.LoadOrStore(attr(i), struct{}{}); visited {
			// drop i silently
		} else {
			out <- i
		}
	}
}

func forkThingSeenAttr(new, old chan<- Thing, inp <-chan Thing, attr func(a Thing) interface{}) {
	defer close(new)
	defer close(old)

	if attr == nil { // Make `nil` value useful
		attr = func(a Thing) interface{} { return a }
	}

	seen := sync.Map{}
	for i := range inp {
		if _, visited := seen.LoadOrStore(attr(i), struct{}{}); visited {
			old <- i
		} else {
			new <- i
		}
	}
}

// TubeThingSeen returns a closure around PipeThingSeen()
// (silently dropping every Thing seen before).
func TubeThingSeen() (tube func(inp <-chan Thing) (out <-chan Thing)) {

	return func(inp <-chan Thing) (out <-chan Thing) {
		return PipeThingSeen(inp)
	}
}

// TubeThingSeenAttr returns a closure around PipeThingSeenAttr()
// (silently dropping every Thing
// whose attribute `attr` was
// seen before).
func TubeThingSeenAttr(attr func(a Thing) interface{}) (tube func(inp <-chan Thing) (out <-chan Thing)) {

	return func(inp <-chan Thing) (out <-chan Thing) {
		return PipeThingSeenAttr(inp, attr)
	}
}

// End of PipeThingSeen/ForkThingSeen - an "I've seen this Thing before" filter / fork
