// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// adjustments and embedding:
// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// original found in $GOROOT/test/chan/sieve2.go

// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sites

import "container/ring"

// Note: pipesiteAdjust imports "container/ring" for the expanding buffer.

// ===========================================================================
// Beg of sitePipeAdjust

// sitePipeAdjust returns a channel to receive
// all `inp`
// buffered by a siteSendProxy process
// before close.
func sitePipeAdjust(inp <-chan site, sizes ...int) (out <-chan site) {
	cap, que := sendsiteProxySizes(sizes...)
	cha := make(chan site, cap)
	go pipesiteAdjust(cha, inp, que)
	return cha
}

// siteTubeAdjust returns a closure around sitePipeAdjust (_, sizes ...int).
func siteTubeAdjust(sizes ...int) (tube func(inp <-chan site) (out <-chan site)) {

	return func(inp <-chan site) (out <-chan site) {
		return sitePipeAdjust(inp, sizes...)
	}
}

// End of sitePipeAdjust
// ===========================================================================

// ===========================================================================
// Beg of sendsiteProxy

func sendsiteProxySizes(sizes ...int) (cap, que int) {

	// CAP is the minimum capacity of the buffered proxy channel in `siteSendProxy`
	const CAP = 10

	// QUE is the minimum initially allocated size of the circular queue in `siteSendProxy`
	const QUE = 16

	cap = CAP
	que = QUE

	if len(sizes) > 0 && sizes[0] > CAP {
		que = sizes[0]
	}

	if len(sizes) > 1 && sizes[1] > QUE {
		que = sizes[1]
	}

	if len(sizes) > 2 {
		panic("siteSendProxy: too many sizes")
	}

	return
}

// siteSendProxy returns a channel to serve as a sending proxy to 'out'.
// Uses a goroutine to receive values from 'out' and store them
// in an expanding buffer, so that sending to 'out' never blocks.
//  Note: the expanding buffer is implemented via "container/ring"
//
// Note: siteSendProxy is kept for the Sieve example
// and other dynamic use to be discovered
// even so it does not fit the pipe tube pattern as sitePipeAdjust does.
func siteSendProxy(out chan<- site, sizes ...int) chan<- site {
	cap, que := sendsiteProxySizes(sizes...)
	cha := make(chan site, cap)
	go pipesiteAdjust(out, cha, que)
	return cha
}

// pipesiteAdjust uses an adjusting buffer to receive from 'inp'
// even so 'out' is not ready to receive yet. The buffer may grow
// until 'inp' is closed and then will shrink by every send to 'out'.
//  Note: the adjusting buffer is implemented via "container/ring"
func pipesiteAdjust(out chan<- site, inp <-chan site, QUE int) {
	defer close(out)
	n := QUE // the allocated size of the circular queue
	first := ring.New(n)
	last := first
	var c chan<- site
	var e site
	ok := true
	for ok {
		c = out
		if first == last {
			c = nil // buffer empty: disable output
		} else {
			e = first.Value.(site)
		}
		select {
		case e, ok = <-inp:
			if ok {
				last.Value = e
				if last.Next() == first {
					last.Link(ring.New(n)) // buffer full: expand it
					n *= 2
				}
				last = last.Next()
			}
		case c <- e:
			first = first.Next()
		}
	}

	for first != last {
		out <- first.Value.(site)
		first = first.Unlink(1) // first.Next()
	}
}

// End of sendsiteProxy
