// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

// ===========================================================================
// Beg of ThingPipeBuffered - a buffered channel with capacity `cap` to receive

// ThingPipeBuffered returns a buffered channel with capacity `cap` to receive
// all `inp`
// before close.
func (inp ThingFrom) ThingPipeBuffered(cap int) (out ThingFrom) {
	cha := make(chan Thing, cap)
	go inp.pipeThingBuffered(cha)
	return cha
}

func (inp ThingFrom) pipeThingBuffered(out ThingInto) {
	defer close(out)
	for i := range inp {
		out <- i
	}
}

// ThingTubeBuffered returns a closure around PipeThingBuffer (cap).
func (inp ThingFrom) ThingTubeBuffered(cap int) (tube func(inp ThingFrom) (out ThingFrom)) {

	return func(inp ThingFrom) (out ThingFrom) {
		return inp.ThingPipeBuffered(cap)
	}
}

// End of ThingPipeBuffered - a buffered channel with capacity `cap` to receive
// ===========================================================================
