// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

// ===========================================================================
// Beg of ThingFanOut

// ThingFanOut returns a slice (of size = size) of channels
// each of which shall receive any inp before close.
func (inp ThingFrom) ThingFanOut(size int) (outS [](ThingFrom)) {
	chaS := make([]chan Thing, size)
	for i := 0; i < size; i++ {
		chaS[i] = make(chan Thing)
	}

	go inp.fanThingOut(chaS...)

	outS = make([]ThingFrom, size)
	for i := 0; i < size; i++ {
		outS[i] = (ThingFrom)(chaS[i]) // convert `chan` to `<-chan`
	}

	return outS
}

// c (inp ThingFrom) fanThingOut(outs ...ThingInto) {
func (inp ThingFrom) fanThingOut(outs ...chan Thing) {

	for i := range inp {
		for o := range outs {
			outs[o] <- i
		}
	}

	for o := range outs {
		close(outs[o])
	}

}

// End of ThingFanOut
// ===========================================================================
