// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by golang.org/x/tools/cmd/bundle. DO NOT EDIT.

package sites

// SiteFrom is a receive-only Site channel
type SiteFrom <-chan Site

// SiteInto is a send-only Site channel
type SiteInto chan<- Site

// ===========================================================================
// Beg of SiteMake creators

// SiteMakeChan returns a new open channel
// (simply a 'chan Site' that is).
// Note: No 'Site-producer' is launched here yet! (as is in all the other functions).
//  This is useful to easily create corresponding variables such as:
/*
var mySitePipelineStartsHere := SiteMakeChan ( ) ;
// ... lot's of code to design and build Your favourite "mySiteWorkflowPipeline"
   // ...
   // ... *before* You start pouring data into it, e.g. simply via:
   for drop := range water {
mySitePipelineStartsHere <- drop ;
   }
close ( mySitePipelineStartsHere ) ;
*/
//  Hint: especially helpful, if Your piping library operates on some hidden (non-exported) type
//  (or on a type imported from elsewhere - and You don't want/need or should(!) have to care.)
//
// Note: as always (except for SitePipeBuffer) the channel is unbuffered.
//
func SiteMakeChan() (out chan Site) {
	return make(chan Site)
}

// End of SiteMake creators
// ===========================================================================

// ===========================================================================
// Beg of SiteChan producers

// SiteChan returns a channel to receive
// all inputs
// before close.
func SiteChan(inp ...Site) (out SiteFrom) {
	cha := make(chan Site)
	go chanSite(cha, inp...)
	return cha
}

func chanSite(out SiteInto, inp ...Site) {
	defer close(out)
	for i := range inp {
		out <- inp[i]
	}
}

// SiteChanSlice returns a channel to receive
// all inputs
// before close.
func SiteChanSlice(inp ...[]Site) (out SiteFrom) {
	cha := make(chan Site)
	go chanSiteSlice(cha, inp...)
	return cha
}

func chanSiteSlice(out SiteInto, inp ...[]Site) {
	defer close(out)
	for i := range inp {
		for j := range inp[i] {
			out <- inp[i][j]
		}
	}
}

// SiteChanFuncNok returns a channel to receive
// all results of generator `gen`
// until `!ok`
// before close.
func SiteChanFuncNok(gen func() (Site, bool)) (out SiteFrom) {
	cha := make(chan Site)
	go chanSiteFuncNok(cha, gen)
	return cha
}

func chanSiteFuncNok(out SiteInto, gen func() (Site, bool)) {
	defer close(out)
	for {
		res, ok := gen() // generate
		if !ok {
			return
		}
		out <- res
	}
}

// SiteChanFuncErr returns a channel to receive
// all results of generator `gen`
// until `err != nil`
// before close.
func SiteChanFuncErr(gen func() (Site, error)) (out SiteFrom) {
	cha := make(chan Site)
	go chanSiteFuncErr(cha, gen)
	return cha
}

func chanSiteFuncErr(out SiteInto, gen func() (Site, error)) {
	defer close(out)
	for {
		res, err := gen() // generate
		if err != nil {
			return
		}
		out <- res
	}
}

// End of SiteChan producers
// ===========================================================================

// ===========================================================================
// Beg of Pipe functions

// PipeFunc returns a channel to receive
// every result of action `act` applied to `inp`
// before close.
// Note: it 'could' be PipeMap for functional people,
// but 'map' has a very different meaning in go lang.
func (inp SiteFrom) PipeFunc(act func(a Site) Site) (out SiteFrom) {
	cha := make(chan Site)
	if act == nil { // Make `nil` value useful
		act = func(a Site) Site { return a }
	}
	go inp.pipeFunc(cha, act)
	return cha
}

func (inp SiteFrom) pipeFunc(out SiteInto, act func(a Site) Site) {
	defer close(out)
	for i := range inp {
		out <- act(i) // apply action
	}
}

// End of Pipe functions
// ===========================================================================

// ===========================================================================
// Beg of Tube closures around Pipe

// TubeFunc returns a closure around PipeFunc (_, act).
func TubeFunc(act func(a Site) Site) (tube func(inp SiteFrom) (out SiteFrom)) {

	return func(inp SiteFrom) (out SiteFrom) {
		return inp.PipeFunc(act)
	}
}

// End of Tube closures around SitePipe
// ===========================================================================

// ===========================================================================
// Beg of Done terminators

// Done
// will apply every `op` to every `inp` and
// returns a channel to receive
// one signal
// upon close.
func (inp SiteFrom) Done(ops ...func(a Site)) (done <-chan struct{}) {
	sig := make(chan struct{})
	go inp.done(sig, ops...)
	return sig
}

func (inp SiteFrom) done(done chan<- struct{}, ops ...func(a Site)) {
	defer close(done)
	for i := range inp {
		for _, op := range ops {
			if op != nil {
				op(i) // apply operation
			}
		}
	}
	done <- struct{}{}
}

// DoneFunc
// will chain every `act` to every `inp` and
// returns a channel to receive
// one signal
// upon close.
func (inp SiteFrom) DoneFunc(acts ...func(a Site) Site) (done <-chan struct{}) {
	sig := make(chan struct{})
	go inp.doneFunc(sig, acts...)
	return sig
}

func (inp SiteFrom) doneFunc(done chan<- struct{}, acts ...func(a Site) Site) {
	defer close(done)
	for i := range inp {
		for _, act := range acts {
			if act != nil {
				i = act(i) // chain action
			}
		}
	}
	done <- struct{}{}
}

// DoneSlice returns a channel to receive
// a slice with every Site received on `inp`
// upon close.
//
//  Note: Unlike Done, DoneSlice sends the fully accumulated slice, not just an event, once upon close of inp.
func (inp SiteFrom) DoneSlice() (done <-chan []Site) {
	sig := make(chan []Site)
	go inp.doneSlice(sig)
	return sig
}

func (inp SiteFrom) doneSlice(done chan<- []Site) {
	defer close(done)
	slice := []Site{}
	for i := range inp {
		slice = append(slice, i)
	}
	done <- slice
}

// End of Done terminators
// ===========================================================================

// ===========================================================================
// Beg of Fini closures

// Fini returns a closure around `Done(ops...)`.
func (inp SiteFrom) Fini(ops ...func(a Site)) func(inp SiteFrom) (done <-chan struct{}) {

	return func(inp SiteFrom) (done <-chan struct{}) {
		return inp.Done(ops...)
	}
}

// FiniFunc returns a closure around `DoneFunc(acts...)`.
func (inp SiteFrom) FiniFunc(acts ...func(a Site) Site) func(inp SiteFrom) (done <-chan struct{}) {

	return func(inp SiteFrom) (done <-chan struct{}) {
		return inp.DoneFunc(acts...)
	}
}

// FiniSlice returns a closure around `DoneSlice()`.
func (inp SiteFrom) FiniSlice() func(inp SiteFrom) (done <-chan []Site) {

	return func(inp SiteFrom) (done <-chan []Site) {
		return inp.DoneSlice()
	}
}

// End of Fini closures
// ===========================================================================

// ===========================================================================
// Beg of Pair functions

// Pair returns a pair of channels to receive every result of inp before close.
//  Note: Yes, it is a VERY simple fanout - but sometimes all You need.
func (inp SiteFrom) Pair() (out1, out2 SiteFrom) {
	cha1 := make(chan Site)
	cha2 := make(chan Site)
	go inp.pair(cha1, cha2)
	return cha1, cha2
}

/* not used - kept for reference only.
func ( inp SiteFrom ) pair ( out1 , out2 SiteInto , inp SiteFrom ) {
	defer close(out1)
	defer close(out2)
	for i := range inp {
		out1 <- i
		out2 <- i
	}
} */

func (inp SiteFrom) pair(out1, out2 SiteInto) {
	defer close(out1)
	defer close(out2)
	for i := range inp {
		select { // send first to whomever is ready to receive
		case out1 <- i:
			out2 <- i
		case out2 <- i:
			out1 <- i
		}
	}
}

// End of Pair functions
// ===========================================================================

// ===========================================================================
// Beg of Fork functions

// Fork returns two channels
// either of which is to receive
// every result of inp
// before close.
func (inp SiteFrom) Fork() (out1, out2 SiteFrom) {
	cha1 := make(chan Site)
	cha2 := make(chan Site)
	go inp.fork(cha1, cha2)
	return cha1, cha2
}

/* not used - kept for reference only.
func ( inp SiteFrom ) fork ( out1 , out2 SiteInto ) {
	defer close(out1)
	defer close(out2)
	for i := range inp {
		out1 <- i
		out2 <- i
	}
} */

func (inp SiteFrom) fork(out1, out2 SiteInto) {
	defer close(out1)
	defer close(out2)
	for i := range inp {
		select { // send first to whomever is ready to receive
		case out1 <- i:
			out2 <- i
		case out2 <- i:
			out1 <- i
		}
	}
}

// End of Fork functions
// ===========================================================================

// ===========================================================================
// Beg of FanIn2 simple binary Fan-In

// FanIn2 returns a channel to receive
// all from both `inp` and `inp2`
// before close.
func (inp SiteFrom) FanIn2(inp2 SiteFrom) (out SiteFrom) {
	cha := make(chan Site)
	go inp.fanIn2(cha, inp2)
	return cha
}

/* not used - kept for reference only.
// (inp SiteFrom) fanin2 as seen in Go Concurrency Patterns
func fanin2 ( out SiteInto , inp , inp2 SiteFrom ) {
	for {
		select {
		case e := <-inp:
			out <- e
		case e := <-inp2:
			out <- e
		}
	}
} */

func (inp SiteFrom) fanIn2(out SiteInto, inp2 SiteFrom) {
	defer close(out)

	var (
		closed bool // we found a chan closed
		ok     bool // did we read successfully?
		e      Site // what we've read
	)

	for !closed {
		select {
		case e, ok = <-inp:
			if ok {
				out <- e
			} else {
				inp = inp2    // swap inp2 into inp
				closed = true // break out of the loop
			}
		case e, ok = <-inp2:
			if ok {
				out <- e
			} else {
				closed = true // break out of the loop				}
			}
		}
	}

	// inp might not be closed yet. Drain it.
	for e = range inp {
		out <- e
	}
}

// End of FanIn2 simple binary Fan-In
// ===========================================================================
