// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sites

import "time"

// ===========================================================================
// Beg of Strew - scatter them

// Strew returns a slice (of size = size) of channels
// one of which shall receive each inp before close.
func (inp SiteFrom) Strew(size int) (outS []SiteFrom) {
	chaS := make(map[chan Site]struct{}, size)
	for i := 0; i < size; i++ {
		chaS[make(chan Site)] = struct{}{}
	}

	go inp.strew(chaS)

	outS = make([]SiteFrom, size)
	i := 0
	for c := range chaS {
		outS[i] = (SiteFrom)(c) // convert `chan Site` to SiteFrom
		i++
	}

	return outS
}

func (inp SiteFrom) strew(outS map[chan Site]struct{}) {

	for i := range inp {
		for !inp.trySend(i, outS) {
			time.Sleep(time.Millisecond * 10) // wait a little before retry
		} // !sent
	} // inp

	for o := range outS {
		close(o)
	}
}

func (static SiteFrom) trySend(inp Site, outS map[chan Site]struct{}) bool {

	for o := range outS {

		select { // try to send
		case o <- inp:
			return true
		default:
			// keep trying
		}

	} // outS
	return false
}

// End of Strew - scatter them
// ===========================================================================
