// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// adjustments and embedding:
// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// original found in $GOROOT/test/chan/sieve2.go

// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

import "container/ring"

// Note: pipeintAdjust imports "container/ring" for the expanding buffer.

// ===========================================================================
// Beg of intPipeAdjust

// intPipeAdjust returns a channel to receive
// all `inp`
// buffered by a intSendProxy process
// before close.
func intPipeAdjust(inp <-chan int, sizes ...int) (out <-chan int) {
	cap, que := sendintProxySizes(sizes...)
	cha := make(chan int, cap)
	go pipeintAdjust(cha, inp, que)
	return cha
}

// intTubeAdjust returns a closure around intPipeAdjust (_, sizes ...int).
func intTubeAdjust(sizes ...int) (tube func(inp <-chan int) (out <-chan int)) {

	return func(inp <-chan int) (out <-chan int) {
		return intPipeAdjust(inp, sizes...)
	}
}

// End of intPipeAdjust
// ===========================================================================

// ===========================================================================
// Beg of sendintProxy

func sendintProxySizes(sizes ...int) (cap, que int) {

	// CAP is the minimum capacity of the buffered proxy channel in `intSendProxy`
	const CAP = 10

	// QUE is the minimum initially allocated size of the circular queue in `intSendProxy`
	const QUE = 16

	cap = CAP
	que = QUE

	if len(sizes) > 0 && sizes[0] > CAP {
		que = sizes[0]
	}

	if len(sizes) > 1 && sizes[1] > QUE {
		que = sizes[1]
	}

	if len(sizes) > 2 {
		panic("intSendProxy: too many sizes")
	}

	return
}

// intSendProxy returns a channel to serve as a sending proxy to 'out'.
// Uses a goroutine to receive values from 'out' and store them
// in an expanding buffer, so that sending to 'out' never blocks.
//  Note: the expanding buffer is implemented via "container/ring"
//
// Note: intSendProxy is kept for the Sieve example
// and other dynamic use to be discovered
// even so it does not fit the pipe tube pattern as intPipeAdjust does.
func intSendProxy(out chan<- int, sizes ...int) chan<- int {
	cap, que := sendintProxySizes(sizes...)
	cha := make(chan int, cap)
	go pipeintAdjust(out, cha, que)
	return cha
}

// pipeintAdjust uses an adjusting buffer to receive from 'inp'
// even so 'out' is not ready to receive yet. The buffer may grow
// until 'inp' is closed and then will shrink by every send to 'out'.
//  Note: the adjusting buffer is implemented via "container/ring"
func pipeintAdjust(out chan<- int, inp <-chan int, QUE int) {
	defer close(out)
	n := QUE // the allocated size of the circular queue
	first := ring.New(n)
	last := first
	var c chan<- int
	var e int
	ok := true
	for ok {
		c = out
		if first == last {
			c = nil // buffer empty: disable output
		} else {
			e = first.Value.(int)
		}
		select {
		case e, ok = <-inp:
			if ok {
				last.Value = e
				if last.Next() == first {
					last.Link(ring.New(n)) // buffer full: expand it
					n *= 2
				}
				last = last.Next()
			}
		case c <- e:
			first = first.Next()
		}
	}

	for first != last {
		out <- first.Value.(int)
		first = first.Unlink(1) // first.Next()
	}
}

// End of sendintProxy
