// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

import "time"

// ===========================================================================
// Beg of intStrew - scatter them

// intStrew returns a slice (of size = size) of channels
// one of which shall receive each inp before close.
func intStrew(inp <-chan int, size int) (outS [](<-chan int)) {
	chaS := make([]chan int, size)
	for i := 0; i < size; i++ {
		chaS[i] = make(chan int)
	}

	go strewint(inp, chaS...)

	outS = make([]<-chan int, size)
	for i := 0; i < size; i++ {
		outS[i] = chaS[i] // convert `chan` to `<-chan`
	}

	return outS
}

// c strewint(inp <-chan int, outS ...chan<- int) {
// Note: go does not convert the passed slice `[]chan int` to `[]chan<- int` automatically.
// So, we do neither here, as we are lazy (we just call an internal helper function).
func strewint(inp <-chan int, outS ...chan int) {

	for i := range inp {
		for !trySendint(i, outS...) {
			time.Sleep(time.Millisecond * 10) // wait a little before retry
		} // !sent
	} // inp

	for o := range outS {
		close(outS[o])
	}
}

func trySendint(inp int, outS ...chan int) bool {

	for o := range outS {

		select { // try to send
		case outS[o] <- inp:
			return true
		default:
			// keep trying
		}

	} // outS
	return false
}

// End of intStrew - scatter them
