// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

import "sync"

// ===========================================================================
// Beg of intFanIn

// intFanIn returns a channel to receive all inputs arriving
// on variadic inps
// before close.
//
//  Note: For each input one go routine is spawned to forward arrivals.
//
// See intFanIn1 in `fan-in1` for another implementation.
//
//  Ref: https://blog.golang.org/pipelines
//  Ref: https://github.com/QuentinPerez/go-stuff/channel/Fan-out-Fan-in/main.go
func intFanIn(inps ...<-chan int) (out <-chan int) {
	cha := make(chan int)

	wg := new(sync.WaitGroup)
	wg.Add(len(inps))

	go fanInintWaitAndClose(cha, wg) // Spawn "close(out)" once all inps are done

	for i := range inps {
		go fanInint(cha, inps[i], wg) // Spawn "output(c)"s
	}

	return cha
}

func fanInint(out chan<- int, inp <-chan int, wg *sync.WaitGroup) {
	defer wg.Done()
	for i := range inp {
		out <- i
	}
}

func fanInintWaitAndClose(out chan<- int, wg *sync.WaitGroup) {
	wg.Wait()
	close(out)
}

// End of intFanIn
