// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipe

import "sync"

// ===========================================================================
// Beg of intPipeSeen/intForkSeen - an "I've seen this int before" filter / forker

// intPipeSeen returns a channel to receive
// all `inp`
// not been seen before
// while silently dropping everything seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
// Note: intPipeFilterNotSeenYet might be a better name, but is fairly long.
func intPipeSeen(inp <-chan int) (out <-chan int) {
	cha := make(chan int)
	go pipeintSeenAttr(cha, inp, nil)
	return cha
}

// intPipeSeenAttr returns a channel to receive
// all `inp`
// whose attribute `attr` has
// not been seen before
// while silently dropping everything seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
// Note: intPipeFilterAttrNotSeenYet might be a better name, but is fairly long.
func intPipeSeenAttr(inp <-chan int, attr func(a int) interface{}) (out <-chan int) {
	cha := make(chan int)
	go pipeintSeenAttr(cha, inp, attr)
	return cha
}

// intForkSeen returns two channels, `new` and `old`,
// where `new` is to receive
// all `inp`
// not been seen before
// and `old`
// all `inp`
// seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
func intForkSeen(inp <-chan int) (new, old <-chan int) {
	cha1 := make(chan int)
	cha2 := make(chan int)
	go forkintSeenAttr(cha1, cha2, inp, nil)
	return cha1, cha2
}

// intForkSeenAttr returns two channels, `new` and `old`,
// where `new` is to receive
// all `inp`
// whose attribute `attr` has
// not been seen before
// and `old`
// all `inp`
// seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
func intForkSeenAttr(inp <-chan int, attr func(a int) interface{}) (new, old <-chan int) {
	cha1 := make(chan int)
	cha2 := make(chan int)
	go forkintSeenAttr(cha1, cha2, inp, attr)
	return cha1, cha2
}

func pipeintSeenAttr(out chan<- int, inp <-chan int, attr func(a int) interface{}) {
	defer close(out)

	if attr == nil { // Make `nil` value useful
		attr = func(a int) interface{} { return a }
	}

	seen := sync.Map{}
	for i := range inp {
		if _, visited := seen.LoadOrStore(attr(i), struct{}{}); visited {
			// drop i silently
		} else {
			out <- i
		}
	}
}

func forkintSeenAttr(new, old chan<- int, inp <-chan int, attr func(a int) interface{}) {
	defer close(new)
	defer close(old)

	if attr == nil { // Make `nil` value useful
		attr = func(a int) interface{} { return a }
	}

	seen := sync.Map{}
	for i := range inp {
		if _, visited := seen.LoadOrStore(attr(i), struct{}{}); visited {
			old <- i
		} else {
			new <- i
		}
	}
}

// intTubeSeen returns a closure around intPipeSeen()
// (silently dropping every int seen before).
func intTubeSeen() (tube func(inp <-chan int) (out <-chan int)) {

	return func(inp <-chan int) (out <-chan int) {
		return intPipeSeen(inp)
	}
}

// intTubeSeenAttr returns a closure around intPipeSeenAttr()
// (silently dropping every int
// whose attribute `attr` was
// seen before).
func intTubeSeenAttr(attr func(a int) interface{}) (tube func(inp <-chan int) (out <-chan int)) {

	return func(inp <-chan int) (out <-chan int) {
		return intPipeSeenAttr(inp, attr)
	}
}

// End of intPipeSeen/intForkSeen - an "I've seen this int before" filter / forker
