// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by golang.org/x/tools/cmd/bundle. DO NOT EDIT.

package rake

// ===========================================================================
// Beg of itemMake creators

// itemMakeChan returns a new open channel
// (simply a 'chan item' that is).
// Note: No 'item-producer' is launched here yet! (as is in all the other functions).
//  This is useful to easily create corresponding variables such as:
/*
var myitemPipelineStartsHere := itemMakeChan()
// ... lot's of code to design and build Your favourite "myitemWorkflowPipeline"
   // ...
   // ... *before* You start pouring data into it, e.g. simply via:
   for drop := range water {
myitemPipelineStartsHere <- drop
   }
close(myitemPipelineStartsHere)
*/
//  Hint: especially helpful, if Your piping library operates on some hidden (non-exported) type
//  (or on a type imported from elsewhere - and You don't want/need or should(!) have to care.)
//
// Note: as always (except for itemPipeBuffer) the channel is unbuffered.
//
func (my *Rake) itemMakeChan() (out chan item) {
	return make(chan item)
}

// End of itemMake creators
// ===========================================================================

// ===========================================================================
// Beg of itemChan producers

// itemChan returns a channel to receive
// all inputs
// before close.
func (my *Rake) itemChan(inp ...item) (out <-chan item) {
	cha := make(chan item)
	go my.chanitem(cha, inp...)
	return cha
}

func (my *Rake) chanitem(out chan<- item, inp ...item) {
	defer close(out)
	for i := range inp {
		out <- inp[i]
	}
}

// itemChanSlice returns a channel to receive
// all inputs
// before close.
func (my *Rake) itemChanSlice(inp ...[]item) (out <-chan item) {
	cha := make(chan item)
	go my.chanitemSlice(cha, inp...)
	return cha
}

func (my *Rake) chanitemSlice(out chan<- item, inp ...[]item) {
	defer close(out)
	for i := range inp {
		for j := range inp[i] {
			out <- inp[i][j]
		}
	}
}

// itemChanFuncNok returns a channel to receive
// all results of generator `gen`
// until `!ok`
// before close.
func (my *Rake) itemChanFuncNok(gen func() (item, bool)) (out <-chan item) {
	cha := make(chan item)
	go my.chanitemFuncNok(cha, gen)
	return cha
}

func (my *Rake) chanitemFuncNok(out chan<- item, gen func() (item, bool)) {
	defer close(out)
	for {
		res, ok := gen() // generate
		if !ok {
			return
		}
		out <- res
	}
}

// itemChanFuncErr returns a channel to receive
// all results of generator `gen`
// until `err != nil`
// before close.
func (my *Rake) itemChanFuncErr(gen func() (item, error)) (out <-chan item) {
	cha := make(chan item)
	go my.chanitemFuncErr(cha, gen)
	return cha
}

func (my *Rake) chanitemFuncErr(out chan<- item, gen func() (item, error)) {
	defer close(out)
	for {
		res, err := gen() // generate
		if err != nil {
			return
		}
		out <- res
	}
}

// End of itemChan producers
// ===========================================================================

// ===========================================================================
// Beg of itemPipe functions

// itemPipeFunc returns a channel to receive
// every result of action `act` applied to `inp`
// before close.
// Note: it 'could' be PipeItemMap for functional people,
// but 'map' has a very different meaning in go lang.
func (my *Rake) itemPipeFunc(inp <-chan item, act func(a item) item) (out <-chan item) {
	cha := make(chan item)
	if act == nil { // Make `nil` value useful
		act = func(a item) item { return a }
	}
	go my.pipeitemFunc(cha, inp, act)
	return cha
}

func (my *Rake) pipeitemFunc(out chan<- item, inp <-chan item, act func(a item) item) {
	defer close(out)
	for i := range inp {
		out <- act(i) // apply action
	}
}

// End of itemPipe functions
// ===========================================================================

// ===========================================================================
// Beg of itemTube closures around itemPipe

// itemTubeFunc returns a closure around PipeItemFunc (_, act).
func (my *Rake) itemTubeFunc(act func(a item) item) (tube func(inp <-chan item) (out <-chan item)) {

	return func(inp <-chan item) (out <-chan item) {
		return my.itemPipeFunc(inp, act)
	}
}

// End of itemTube closures around itemPipe
// ===========================================================================

// ===========================================================================
// Beg of itemDone terminators

// itemDone returns a channel to receive
// one signal before close after `inp` has been drained.
func (my *Rake) itemDone(inp <-chan item) (done <-chan struct{}) {
	sig := make(chan struct{})
	go my.doneitem(sig, inp)
	return sig
}

func (my *Rake) doneitem(done chan<- struct{}, inp <-chan item) {
	defer close(done)
	for i := range inp {
		_ = i // Drain inp
	}
	done <- struct{}{}
}

// itemDoneSlice returns a channel to receive
// a slice with every item received on `inp`
// before close.
//
// Note: Unlike itemDone, DoneItemSlice sends the fully accumulated slice, not just an event, once upon close of inp.
func (my *Rake) itemDoneSlice(inp <-chan item) (done <-chan []item) {
	sig := make(chan []item)
	go my.doneitemSlice(sig, inp)
	return sig
}

func (my *Rake) doneitemSlice(done chan<- []item, inp <-chan item) {
	defer close(done)
	slice := []item{}
	for i := range inp {
		slice = append(slice, i)
	}
	done <- slice
}

// itemDoneFunc returns a channel to receive
// one signal after `act` has been applied to every `inp`
// before close.
func (my *Rake) itemDoneFunc(inp <-chan item, act func(a item)) (done <-chan struct{}) {
	sig := make(chan struct{})
	if act == nil {
		act = func(a item) { return }
	}
	go my.doneitemFunc(sig, inp, act)
	return sig
}

func (my *Rake) doneitemFunc(done chan<- struct{}, inp <-chan item, act func(a item)) {
	defer close(done)
	for i := range inp {
		act(i) // apply action
	}
	done <- struct{}{}
}

// End of itemDone terminators
// ===========================================================================

// ===========================================================================
// Beg of itemFini closures

// itemFini returns a closure around `itemDone(_)`.
func (my *Rake) itemFini() func(inp <-chan item) (done <-chan struct{}) {

	return func(inp <-chan item) (done <-chan struct{}) {
		return my.itemDone(inp)
	}
}

// itemFiniSlice returns a closure around `itemDoneSlice(_)`.
func (my *Rake) itemFiniSlice() func(inp <-chan item) (done <-chan []item) {

	return func(inp <-chan item) (done <-chan []item) {
		return my.itemDoneSlice(inp)
	}
}

// itemFiniFunc returns a closure around `itemDoneFunc(_, act)`.
func (my *Rake) itemFiniFunc(act func(a item)) func(inp <-chan item) (done <-chan struct{}) {

	return func(inp <-chan item) (done <-chan struct{}) {
		return my.itemDoneFunc(inp, act)
	}
}

// End of itemFini closures
// ===========================================================================

// ===========================================================================
// Beg of itemPair functions

// itemPair returns a pair of channels to receive every result of inp before close.
//  Note: Yes, it is a VERY simple fanout - but sometimes all You need.
func (my *Rake) itemPair(inp <-chan item) (out1, out2 <-chan item) {
	cha1 := make(chan item)
	cha2 := make(chan item)
	go my.pairitem(cha1, cha2, inp)
	return cha1, cha2
}

/* not used - kept for reference only.
func (my *Rake) pairitem(out1, out2 chan<- item, inp <-chan item) {
	defer close(out1)
	defer close(out2)
	for i := range inp {
		out1 <- i
		out2 <- i
	}
} */

func (my *Rake) pairitem(out1, out2 chan<- item, inp <-chan item) {
	defer close(out1)
	defer close(out2)
	for i := range inp {
		select { // send first to whomever is ready to receive
		case out1 <- i:
			out2 <- i
		case out2 <- i:
			out1 <- i
		}
	}
}

// End of itemPair functions
// ===========================================================================

// ===========================================================================
// Beg of itemFork functions

// itemFork returns two channels
// either of which is to receive
// every result of inp
// before close.
func (my *Rake) itemFork(inp <-chan item) (out1, out2 <-chan item) {
	cha1 := make(chan item)
	cha2 := make(chan item)
	go my.forkitem(cha1, cha2, inp)
	return cha1, cha2
}

/* not used - kept for reference only.
func (my *Rake) forkitem(out1, out2 chan<- item, inp <-chan item) {
	defer close(out1)
	defer close(out2)
	for i := range inp {
		out1 <- i
		out2 <- i
	}
} */

func (my *Rake) forkitem(out1, out2 chan<- item, inp <-chan item) {
	defer close(out1)
	defer close(out2)
	for i := range inp {
		select { // send first to whomever is ready to receive
		case out1 <- i:
			out2 <- i
		case out2 <- i:
			out1 <- i
		}
	}
}

// End of itemFork functions
// ===========================================================================

// ===========================================================================
// Beg of itemFanIn2 simple binary Fan-In

// itemFanIn2 returns a channel to receive all to receive all from both `inp1` and `inp2` before close.
func (my *Rake) itemFanIn2(inp1, inp2 <-chan item) (out <-chan item) {
	cha := make(chan item)
	go my.fanIn2item(cha, inp1, inp2)
	return cha
}

/* not used - kept for reference only.
// (my *Rake) fanin2item as seen in Go Concurrency Patterns
func fanin2item(out chan<- item, inp1, inp2 <-chan item) {
	for {
		select {
		case e := <-inp1:
			out <- e
		case e := <-inp2:
			out <- e
		}
	}
} */

func (my *Rake) fanIn2item(out chan<- item, inp1, inp2 <-chan item) {
	defer close(out)

	var (
		closed bool // we found a chan closed
		ok     bool // did we read successfully?
		e      item // what we've read
	)

	for !closed {
		select {
		case e, ok = <-inp1:
			if ok {
				out <- e
			} else {
				inp1 = inp2   // swap inp2 into inp1
				closed = true // break out of the loop
			}
		case e, ok = <-inp2:
			if ok {
				out <- e
			} else {
				closed = true // break out of the loop				}
			}
		}
	}

	// inp1 might not be closed yet. Drain it.
	for e = range inp1 {
		out <- e
	}
}

// End of itemFanIn2 simple binary Fan-In
// ===========================================================================
