// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// adjustments and embedding:
// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// original found in $GOROOT/test/chan/sieve2.go

// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package rake

import "container/ring"

// Note: pipeitemAdjust imports "container/ring" for the expanding buffer.

// ===========================================================================
// Beg of itemPipeAdjust

// itemPipeAdjust returns a channel to receive
// all `inp`
// buffered by a itemSendProxy process
// before close.
func (inp itemFrom) itemPipeAdjust(sizes ...int) (out itemFrom) {
	cap, que := senditemProxySizes(sizes...)
	cha := make(chan item, cap)
	go inp.pipeitemAdjust(cha, que)
	return cha
}

// itemTubeAdjust returns a closure around itemPipeAdjust (_, sizes ...int).
func (inp itemFrom) itemTubeAdjust(sizes ...int) (tube func(inp itemFrom) (out itemFrom)) {

	return func(inp itemFrom) (out itemFrom) {
		return inp.itemPipeAdjust(sizes...)
	}
}

// End of itemPipeAdjust
// ===========================================================================

// ===========================================================================
// Beg of senditemProxy

func senditemProxySizes(sizes ...int) (cap, que int) {

	// CAP is the minimum capacity of the buffered proxy channel in `itemSendProxy`
	const CAP = 10

	// QUE is the minimum initially allocated size of the circular queue in `itemSendProxy`
	const QUE = 16

	cap = CAP
	que = QUE

	if len(sizes) > 0 && sizes[0] > CAP {
		que = sizes[0]
	}

	if len(sizes) > 1 && sizes[1] > QUE {
		que = sizes[1]
	}

	if len(sizes) > 2 {
		panic("itemSendProxy: too many sizes")
	}

	return
}

// itemSendProxy returns a channel to serve as a sending proxy to 'out'.
// Uses a goroutine to receive values from 'out' and store them
// in an expanding buffer, so that sending to 'out' never blocks.
//  Note: the expanding buffer is implemented via "container/ring"
//
// Note: itemSendProxy is kept for the Sieve example
// and other dynamic use to be discovered
// even so it does not fit the pipe tube pattern as itemPipeAdjust does.
func itemSendProxy(out itemInto, sizes ...int) (send itemInto) {
	cap, que := senditemProxySizes(sizes...)
	cha := make(chan item, cap)
	go (itemFrom)(cha).pipeitemAdjust(out, que)
	return cha
}

// pipeitemAdjust uses an adjusting buffer to receive from 'inp'
// even so 'out' is not ready to receive yet. The buffer may grow
// until 'inp' is closed and then will shrink by every send to 'out'.
//  Note: the adjusting buffer is implemented via "container/ring"
func (inp itemFrom) pipeitemAdjust(out itemInto, QUE int) {
	defer close(out)
	n := QUE // the allocated size of the circular queue
	first := ring.New(n)
	last := first
	var c itemInto
	var e item
	ok := true
	for ok {
		c = out
		if first == last {
			c = nil // buffer empty: disable output
		} else {
			e = first.Value.(item)
		}
		select {
		case e, ok = <-inp:
			if ok {
				last.Value = e
				if last.Next() == first {
					last.Link(ring.New(n)) // buffer full: expand it
					n *= 2
				}
				last = last.Next()
			}
		case c <- e:
			first = first.Next()
		}
	}

	for first != last {
		out <- first.Value.(item)
		first = first.Unlink(1) // first.Next()
	}
}

// End of senditemProxy
// ===========================================================================
