// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package rake

// ===========================================================================
// Beg of itemPipeEnter/Leave - Flapdoors observed by a Waiter

// itemWaiter - as implemented by `*sync.WaitGroup` -
// attends Flapdoors and keeps counting
// who enters and who leaves.
//
// Use itemDoneWait to learn about
// when the facilities are closed.
//
// Note: You may also use Your provided `*sync.WaitGroup.Wait()`
// to know when to close the facilities.
// Just: itemDoneWait is more convenient
// as it also closes the primary channel for You.
//
// Just make sure to have _all_ entrances and exits attended,
// and `Wait()` only *after* You've started flooding the facilities.
type itemWaiter interface {
	Add(delta int)
	Done()
	Wait()
}

// Note: The name is intentionally generic in order to avoid eventual multiple-declaration clashes.

// itemPipeEnter returns a channel to receive
// all `inp`
// and registers throughput
// as arrival
// on the given `sync.WaitGroup`
// until close.
func (my *Rake) itemPipeEnter(inp <-chan item, wg itemWaiter) (out <-chan item) {
	cha := make(chan item)
	go my.pipeitemEnter(cha, wg, inp)
	return cha
}

// itemPipeLeave returns a channel to receive
// all `inp`
// and registers throughput
// as departure
// on the given `sync.WaitGroup`
// until close.
func (my *Rake) itemPipeLeave(inp <-chan item, wg itemWaiter) (out <-chan item) {
	cha := make(chan item)
	go my.pipeitemLeave(cha, wg, inp)
	return cha
}

// itemDoneLeave returns a channel to receive
// one signal after
// all throughput on `inp`
// has been registered
// as departure
// on the given `sync.WaitGroup`
// before close.
func (my *Rake) itemDoneLeave(inp <-chan item, wg itemWaiter) (done <-chan struct{}) {
	sig := make(chan struct{})
	go my.doneitemLeave(sig, wg, inp)
	return sig
}

func (my *Rake) pipeitemEnter(out chan<- item, wg itemWaiter, inp <-chan item) {
	defer close(out)
	for i := range inp {
		wg.Add(1)
		out <- i
	}
}

func (my *Rake) pipeitemLeave(out chan<- item, wg itemWaiter, inp <-chan item) {
	defer close(out)
	for i := range inp {
		out <- i
		wg.Done()
	}
}

func (my *Rake) doneitemLeave(done chan<- struct{}, wg itemWaiter, inp <-chan item) {
	defer close(done)
	for i := range inp {
		_ = i // discard
		wg.Done()
	}
	done <- struct{}{}
}

// itemTubeEnter returns a closure around itemPipeEnter (_, wg)
// registering throughput
// as arrival
// on the given `sync.WaitGroup`.
func (my *Rake) itemTubeEnter(wg itemWaiter) (tube func(inp <-chan item) (out <-chan item)) {

	return func(inp <-chan item) (out <-chan item) {
		return my.itemPipeEnter(inp, wg)
	}
}

// itemTubeLeave returns a closure around itemPipeLeave (_, wg)
// registering throughput
// as departure
// on the given `sync.WaitGroup`.
func (my *Rake) itemTubeLeave(wg itemWaiter) (tube func(inp <-chan item) (out <-chan item)) {

	return func(inp <-chan item) (out <-chan item) {
		return my.itemPipeLeave(inp, wg)
	}
}

// itemFiniLeave returns a closure around `itemDoneLeave(_, wg)`
// registering throughput
// as departure
// on the given `sync.WaitGroup`.
func (my *Rake) itemFiniLeave(wg itemWaiter) func(inp <-chan item) (done <-chan struct{}) {

	return func(inp <-chan item) (done <-chan struct{}) {
		return my.itemDoneLeave(inp, wg)
	}
}

// itemDoneWait returns a channel to receive
// one signal
// after wg.Wait() has returned and inp has been closed
// before close.
//
// Note: Use only *after* You've started flooding the facilities.
func (my *Rake) itemDoneWait(inp chan<- item, wg itemWaiter) (done <-chan struct{}) {
	cha := make(chan struct{})
	go my.doneitemWait(cha, inp, wg)
	return cha
}

func (my *Rake) doneitemWait(done chan<- struct{}, inp chan<- item, wg itemWaiter) {
	defer close(done)
	wg.Wait()
	close(inp)
	done <- struct{}{} // not really needed - but looks better
}

// itemFiniWait returns a closure around `DoneitemWait(_, wg)`.
func (my *Rake) itemFiniWait(wg itemWaiter) func(inp chan<- item) (done <-chan struct{}) {

	return func(inp chan<- item) (done <-chan struct{}) {
		return my.itemDoneWait(inp, wg)
	}
}

// End of itemPipeEnter/Leave - Flapdoors observed by a Waiter
// ===========================================================================
