// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package rake

import "sync"

// ===========================================================================
// Beg of PipeSeen/ForkSeen - an "I've seen this item before" filter / forker

// PipeSeen returns a channel to receive
// all `inp`
// not been seen before
// while silently dropping everything seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
//  Note: PipeFilterNotSeenYet might be a better name, but is fairly long.
func (inp itemFrom) PipeSeen() (out itemFrom) {
	cha := make(chan item)
	go inp.pipeSeenAttr(cha, nil)
	return cha
}

// PipeSeenAttr returns a channel to receive
// all `inp`
// whose attribute `attr` has
// not been seen before
// while silently dropping everything seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
//  Note: PipeFilterAttrNotSeenYet might be a better name, but is fairly long.
func (inp itemFrom) PipeSeenAttr(attr func(a item) interface{}) (out itemFrom) {
	cha := make(chan item)
	go inp.pipeSeenAttr(cha, attr)
	return cha
}

// ForkSeen returns two channels, `new` and `old`,
// where `new` is to receive
// all `inp`
// not been seen before
// and `old`
// all `inp`
// seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
func (inp itemFrom) ForkSeen() (new, old itemFrom) {
	cha1 := make(chan item)
	cha2 := make(chan item)
	go inp.forkSeenAttr(cha1, cha2, nil)
	return cha1, cha2
}

// ForkSeenAttr returns two channels, `new` and `old`,
// where `new` is to receive
// all `inp`
// whose attribute `attr` has
// not been seen before
// and `old`
// all `inp`
// seen before
// (internally growing a `sync.Map` to discriminate)
// until close.
func (inp itemFrom) ForkSeenAttr(attr func(a item) interface{}) (new, old itemFrom) {
	cha1 := make(chan item)
	cha2 := make(chan item)
	go inp.forkSeenAttr(cha1, cha2, attr)
	return cha1, cha2
}

func (inp itemFrom) pipeSeenAttr(out itemInto, attr func(a item) interface{}) {
	defer close(out)

	if attr == nil { // Make `nil` value useful
		attr = func(a item) interface{} { return a }
	}

	seen := sync.Map{}
	for i := range inp {
		if _, visited := seen.LoadOrStore(attr(i), struct{}{}); visited {
			// drop i silently
		} else {
			out <- i
		}
	}
}

func (inp itemFrom) forkSeenAttr(new, old itemInto, attr func(a item) interface{}) {
	defer close(new)
	defer close(old)

	if attr == nil { // Make `nil` value useful
		attr = func(a item) interface{} { return a }
	}

	seen := sync.Map{}
	for i := range inp {
		if _, visited := seen.LoadOrStore(attr(i), struct{}{}); visited {
			old <- i
		} else {
			new <- i
		}
	}
}

// TubeSeen returns a closure around PipeSeen()
// (silently dropping every item seen before).
func (inp itemFrom) TubeSeen() (tube func(inp itemFrom) (out itemFrom)) {

	return func(inp itemFrom) (out itemFrom) {
		return inp.PipeSeen()
	}
}

// TubeSeenAttr returns a closure around PipeSeenAttr(attr)
// (silently dropping every item
// whose attribute `attr` was
// seen before).
func (inp itemFrom) TubeSeenAttr(attr func(a item) interface{}) (tube func(inp itemFrom) (out itemFrom)) {

	return func(inp itemFrom) (out itemFrom) {
		return inp.PipeSeenAttr(attr)
	}
}

// End of PipeSeen/ForkSeen - an "I've seen this item before" filter / forker
// ===========================================================================
