// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

// Copyright 2017 Andreas Pannewitz. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sites

// ===========================================================================
// Beg of SitePipeEnter/Leave - Flapdoors observed by a Waiter

// SiteWaiter - as implemented by `*sync.WaitGroup` -
// attends Flapdoors and keeps counting
// who enters and who leaves.
//
// Use DoneSiteWait to learn about
// when the facilities are closed.
//
// Note: You may also use Your provided `*sync.WaitGroup.Wait()`
// to know when to close the facilities.
// Just: DoneSiteWait is more convenient
// as it also closes the primary channel.
//
// Just make sure to have _all_ entrances and exits attended,
// and `Wait()` only *after* You've started flooding the facilities.
type SiteWaiter interface {
	Add(delta int)
	Done()
	Wait()
}

// Note: Name is generic in order to avoid multiple-declaration clashes.

// SitePipeEnter returns a channel to receive
// all `inp`
// and registers throughput
// as arrival
// on the given `sync.WaitGroup`
// until close.
func SitePipeEnter(inp <-chan Site, wg SiteWaiter) (out <-chan Site) {
	cha := make(chan Site)
	go pipeSiteEnter(cha, wg, inp)
	return cha
}

// SitePipeLeave returns a channel to receive
// all `inp`
// and registers throughput
// as departure
// on the given `sync.WaitGroup`
// until close.
func SitePipeLeave(inp <-chan Site, wg SiteWaiter) (out <-chan Site) {
	cha := make(chan Site)
	go pipeSiteLeave(cha, wg, inp)
	return cha
}

func pipeSiteEnter(out chan<- Site, wg SiteWaiter, inp <-chan Site) {
	defer close(out)
	for i := range inp {
		wg.Add(1)
		out <- i
	}
}

func pipeSiteLeave(out chan<- Site, wg SiteWaiter, inp <-chan Site) {
	defer close(out)
	for i := range inp {
		out <- i
		wg.Done()
	}
}

// SiteTubeEnter returns a closure around SitePipeEnter (_, wg)
// registering throughput
// on the given `sync.WaitGroup`
// as arrival.
func SiteTubeEnter(wg SiteWaiter) (tube func(inp <-chan Site) (out <-chan Site)) {

	return func(inp <-chan Site) (out <-chan Site) {
		return SitePipeEnter(inp, wg)
	}
}

// SiteTubeLeave returns a closure around SitePipeLeave (_, wg)
// registering throughput
// on the given `sync.WaitGroup`
// as departure.
func SiteTubeLeave(wg SiteWaiter) (tube func(inp <-chan Site) (out <-chan Site)) {

	return func(inp <-chan Site) (out <-chan Site) {
		return SitePipeLeave(inp, wg)
	}
}

// SiteDoneWait returns a channel to receive
// one signal
// after wg.Wait() has returned and inp has been closed
// before close.
//
// Note: Use only *after* You've started flooding the facilities.
func SiteDoneWait(inp chan<- Site, wg SiteWaiter) (done <-chan struct{}) {
	cha := make(chan struct{})
	go doneSiteWait(cha, inp, wg)
	return cha
}

func doneSiteWait(done chan<- struct{}, inp chan<- Site, wg SiteWaiter) {
	defer close(done)
	wg.Wait()
	close(inp)
	done <- struct{}{} // not really needed - but looks better
}

// SiteFiniWait returns a closure around `DoneSiteWait(_, wg)`.
func SiteFiniWait(wg SiteWaiter) func(inp chan<- Site) (done <-chan struct{}) {

	return func(inp chan<- Site) (done <-chan struct{}) {
		return SiteDoneWait(inp, wg)
	}
}

// End of SitePipeEnter/Leave - Flapdoors observed by a Waiter
